apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: workload-with-sidecar
  namespace: product
spec:
  # Where to apply the plugin. Remember you have to select a workload that is a gateway, or has a sidecar inside
  selector:
    matchLabels:
      istio: workload-with-sidecar

  # Where to get the plugin
  url: https://github.com/achetronic/tnep/releases/download/v0.1.0/plugin.wasm
  imagePullPolicy: Always

  # When to apply the plugin
  # Ref: https://istio.io/latest/docs/reference/config/proxy_extensions/wasm-plugin/#PluginType
  type: HTTP
  phase: AUTHN

  # Params to pass to the plugin
  pluginConfig:
    trusted_networks:
      - 35.0.0.0/8
      - 10.0.0.0/8
      - 34.0.0.0/8

    injected_header_name: x-real-client-ip
    overwrite_header_on_exists: true
